### PR TITLE
Toolbar and hero section 1

### PR DESCRIPTION
**Pull request by studiosnabeel**
Created Tool bar and Hero section of the website using HTML & CSS.
Linters used to check and fix errors.
Worked on the Mobile section of the website.
Work done according to Github flow.

### CODE REVIEW

**Review by mgmediaweb — CHANGES_REQUESTED** [review]
Hi @studiosnabeel , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that  linter are not passed

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by Alfredbis29 — CHANGES_REQUESTED** [review]
### Hi @studiosnabeel , 

📝👌 **Your project highlights** 🔥😎 
- General Requirements ✔

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

**Comment by studiosnabeel** [comment]
Hi this is only my 5th day at Microverse 🙃. Your advice is much
appreciated. Everything you mentioned above makes sense but how will I
manage to complete this in this week's deadline?😅. I have another project
to do after this as well and today is Friday. So are you actually
suggesting that I repeat the first week? 🙆

**Comment by studiosnabeel** [comment]
Hi i have questions can you come on slack

**Review by sumairq — APPROVED** [review]
### Hi @studiosnabeel  , 



Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Good commit history
✔️Linters are passing
✔️Very professional README
✔️Correct Github flow
✔️Descriptive PR
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by studiosnabeel** [comment]
Awesome, thank you so much!

**Review by bimbolabuari — COMMENTED** [review]
Hello @studiosnabeel  👋, 

_This is an additional review as a result of the second opinion request._

- I can see the issue is already resolved and your project is approved 👍 

 Keep rocking 🚀!

**Pull request merged**
